### PR TITLE
Fat Titz

### PR DESCRIPTION
**Pull request by Frosty54**
Can you make fat titz (latest stockfish with fat titz net) pls for android (armv7, arm8).

### CODE REVIEW

**Comment by Joachim26** [comment]
LOL a lot of commits...
If it would be possible to compile FatTitz 1 or 2 for Android I would have done it. So my answer is: NO, not possible.

**Comment by Frosty54** [comment]
Ok, can you update it for using embedded srockfish 47mb nets in this engine, is it possible to make for android?
https://github.com/FireFather/fire

**Comment by Joachim26** [comment]
Don't understand your question, but answer is most likely again: No.

**Comment by Frosty54** [comment]
Ok, what's you planning try to compile next?

**Comment by Joachim26** [comment]
Would you please be so kind and close this PR? 
Thanks in advance.
This here is the wrong place for asking and answering your questionS! I guess you know that very well.

**Comment by Frosty54** [comment]
Baaaaad

**Pull request closed without merging**
